# topic_name: freq(double)
# topic_name: -1 (it will be recorded at publish freq)
#           : 0 (it will not be recorded)

# For topic_name same regular expressions cli can be used: ex. "/realsense(.*)" : 0
# used by default rosbag: http://wiki.ros.org/rosbag/Commandline

# if there is a topic in a namespace which has been excluded using regular expressions: 
#   to record that topic put that topic before the regular expression


#--------------throttled topics----------------------#
"/string_1": 1
#--------------throttled topics----------------------#


#----------not throttled topics-----------------------#
"/int_1": -1
#----------not throttled topics-----------------------#


#--------------ignored topics----------------------#
"/string_(.*)": 0
"/rosout(.*)": 0
#--------------ignored topics----------------------#
